//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Prefabs/Weapons/BasicWeapon/EctoGearInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EctoGearInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EctoGearInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""EctoGearInputActions"",
    ""maps"": [
        {
            ""name"": ""EctoGear"",
            ""id"": ""38c25efa-5e46-4da8-a1fe-48db42ae87cc"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""a91f8a0a-ef17-4eb8-84c2-1fe6be5ecdb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81946633-0690-454d-9f6a-b4e7c698a6ac"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // EctoGear
        m_EctoGear = asset.FindActionMap("EctoGear", throwIfNotFound: true);
        m_EctoGear_Fire = m_EctoGear.FindAction("Fire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // EctoGear
    private readonly InputActionMap m_EctoGear;
    private IEctoGearActions m_EctoGearActionsCallbackInterface;
    private readonly InputAction m_EctoGear_Fire;
    public struct EctoGearActions
    {
        private @EctoGearInputActions m_Wrapper;
        public EctoGearActions(@EctoGearInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire => m_Wrapper.m_EctoGear_Fire;
        public InputActionMap Get() { return m_Wrapper.m_EctoGear; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EctoGearActions set) { return set.Get(); }
        public void SetCallbacks(IEctoGearActions instance)
        {
            if (m_Wrapper.m_EctoGearActionsCallbackInterface != null)
            {
                @Fire.started -= m_Wrapper.m_EctoGearActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_EctoGearActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_EctoGearActionsCallbackInterface.OnFire;
            }
            m_Wrapper.m_EctoGearActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
            }
        }
    }
    public EctoGearActions @EctoGear => new EctoGearActions(this);
    public interface IEctoGearActions
    {
        void OnFire(InputAction.CallbackContext context);
    }
}
